# Generated by Django 4.2.7 on 2023-11-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], default='USD', max_length=3)),
                ('stripe_item_price_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
